rmarkdown::render("validation_files/1.1_validation_power_between_1x2.Rmd")
rmarkdown::render("validation_files/1.1_validation_power_between_1x2.md", output_format = "pdf_document")
rmarkdown::render("validation_files/1.2_validation_power_between_1x3.Rmd")
rmarkdown::render("validation_files/1.2_validation_power_between_1x3.md", output_format = "pdf_document")
rmarkdown::render("validation_files/1.3_validation_power_between_Brysbaert_1x3.Rmd")
rmarkdown::render("validation_files/1.3_validation_power_between_Brysbaert_1x3.md", output_format = "pdf_document")
rmarkdown::render("validation_files/2.1_validation_power_within_2x1.Rmd")
rmarkdown::render("validation_files/2.1_validation_power_within_2x1.md", output_format = "pdf_document")
rmarkdown::render("validation_files/2.2_validation_power_within_3x1.Rmd")
rmarkdown::render("validation_files/2.2_validation_power_within_3x1.md", output_format = "pdf_document")
rmarkdown::render("validation_files/2.3_validation_power_within_Brysbaert_3x1.Rmd")
rmarkdown::render("validation_files/2.3_validation_power_within_Brysbaert_3x1.md", output_format = "pdf_document")
rmarkdown::render("validation_files/3.1_validation_power_between_within_2x2.Rmd")
rmarkdown::render("validation_files/3.1_validation_power_between_within_2x2.md", output_format = "pdf_document")
rmarkdown::render("validation_files/3.2_validation_power_within_within_2x2_Amsel.Rmd")
rmarkdown::render("validation_files/3.2_validation_power_within_within_2x2_Amsel.md", output_format = "pdf_document")
rmarkdown::render("validation_files/3.3_validation_power_within_within_Provin_Schutz_Not_Complete.Rmd")
rmarkdown::render("validation_files/3.3_validation_power_within_within_Provin_Schutz_Not_Complete.md", output_format = "pdf_document")
rmarkdown::render("validation_files/4.1_error_control_in_exploratory_ANOVA.Rmd")
rmarkdown::render("validation_files/4.1_error_control_in_exploratory_ANOVA.md", output_format = "pdf_document")

rmarkdown::render("validation_files/4.3_analytic_power_functions.Rmd")
rmarkdown::render("validation_files/4.3_analytic_power_functions.Rmd", output_format = "pdf_document")
